APPLICATION_NAME = 'SocialSynchro'
CONSUMER_KEY_LENGTH = 32
SECRET_CONSUMER_KEY_LENGTH = 32

REQUEST_EXPIRATION_TIME_SECONDS = 300

TWITTER_SERVICE_NAME = 'Twitter'
TWITTER_UPDATE_STATUS_LIMIT = 300
TWITTER_DESTROY_STATUS_LIMIT = 300
TWITTER_RESET_UPDATE_STATUS_SECONDS = 10800
TWITTER_RESET_DESTROY_STATUS_SECONDS = 10800