# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-26 10:13
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(max_length=20)),
                ('consumer_key', models.CharField(max_length=50, unique=True)),
                ('secret_consumer_key', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterRateLimits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_name', models.CharField(max_length=20, unique=True)),
                ('init_date', models.DateTimeField(default=datetime.datetime(2019, 9, 26, 10, 13, 43, 15156, tzinfo=utc))),
                ('limit', models.IntegerField(default=300)),
                ('remaining', models.IntegerField(default=300)),
                ('reset', models.DurationField(default=datetime.timedelta(0, 10800))),
            ],
        ),
        migrations.CreateModel(
            name='TwitterToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_token', models.CharField(max_length=27, unique=True, validators=[django.core.validators.MinLengthValidator(27)])),
                ('verifier', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(32)])),
            ],
        ),
    ]
