# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-26 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterratelimits',
            name='init_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
