# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-26 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190926_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(default=b'SocialSynchro', max_length=20, unique=True)),
                ('consumer_key', models.CharField(max_length=32, unique=True)),
                ('secret_consumer_key', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
