# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-27 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20190926_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterratelimits',
            name='limit',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='twitterratelimits',
            name='remaining',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='twitterratelimits',
            name='request_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='twitterratelimits',
            name='reset',
            field=models.IntegerField(default=10800),
        ),
    ]
