# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-27 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20190927_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestcounter',
            old_name='last_reset_date',
            new_name='init_date',
        ),
    ]
