# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-09-28 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20190927_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestcounter',
            old_name='request_name',
            new_name='endpoint',
        ),
    ]
