# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-14 12:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20190928_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=30, unique=True, verbose_name=[django.core.validators.MinLengthValidator(30)])),
                ('token', models.CharField(max_length=50)),
            ],
        ),
    ]
