# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-15 13:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_facebooktoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebooktoken',
            name='state',
            field=models.CharField(max_length=187, unique=True, verbose_name=[django.core.validators.MinLengthValidator(187)]),
        ),
    ]
