# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-15 13:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20191115_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebooktoken',
            name='state',
            field=models.CharField(max_length=30, unique=True, verbose_name=[django.core.validators.MinLengthValidator(30)]),
        ),
        migrations.AlterField(
            model_name='facebooktoken',
            name='token',
            field=models.CharField(max_length=187, verbose_name=[django.core.validators.MinLengthValidator(187)]),
        ),
    ]
