# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-15 15:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20191115_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebooktoken',
            name='state',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(30)]),
        ),
    ]
