# Generated by Django 2.2.1 on 2020-01-03 23:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20191115_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviantArtToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(30)])),
                ('code', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='applicationkey',
            name='application_name',
            field=models.CharField(default='SocialSynchro', max_length=20, unique=True),
        ),
    ]
